export enum DocumentStatus {
  ACCEPTED = "Accepted",
  REJECTED = "Rejected",

  PENDING = "PENDING",
  IC_APPROVED = "IC_APPROVED",
  IC_REJECTED = "IC_REJECTED",
  DNA_APPROVED = "DNA_APPROVED",
  DNA_REJECTED = "DNA_REJECTED",
}
